### ISSUE TITLE
Global CSS cannot be imported from within node_modules.

### ISSUE THREAD

**Issue by PrakashTirumalareddy** [alDuncanson/react-address-autocomplete#9]
Getting this issue here.. Can you please help?

./node_modules/@alDuncanson/react-address-autocomplete/lib/style.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@alDuncanson/react-address-autocomplete/lib/index.js

**Comment by alDuncanson** [comment]
Hi @PrakashTirumalareddy , yes you cannot import the css from within the node module. Were you just trying to add custom styles to the component?

**Comment by PrakashTirumalareddy** [comment]
@alDuncanson  Thanks for replying. I did the following:
yarn add @alduncanson/react-address-autocomplete
import AddressInput from '@alDuncanson/react-address-autocomplete'

I get this error as soon as I did the import.

error - ./node_modules/@alDuncanson/react-address-autocomplete/lib/style.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@alDuncanson/react-address-autocomplete/lib/index.js

**Comment by alDuncanson** [comment]
Interesting, I'll look into this tonight.

In the meantime, try rolling back to [v1.0.0](https://www.npmjs.com/package/@alduncanson/react-address-autocomplete/v/1.0.0) and see if that fixes the issue for you.

**Comment by PrakashTirumalareddy** [comment]
@alDuncanson Not sure what is wrong but I am getting the following error:
Any advise?

error - ./node_modules/@alDuncanson/react-address-autocomplete/lib/style.css
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@alDuncanson/react-address-autocomplete/lib/index.js
/Users/prakash/Personal/project/frontend/node_modules/@alDuncanson/react-address-autocomplete/lib/style.css:1
.Address_Input {
^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/prakash/Personal/project/frontend/node_modules/@alDuncanson/react-address-autocomplete/lib/index.js:13:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.@alDuncanson/react-address-autocomplete (/Users/prakash/Personal/project/frontend/.next/server/static/development/pages/register.js:541:18)
    at __webpack_require__ (/Users/prakash/Personal/project/frontend/.next/server/static/development/pages/register.js:23:31)
ModuleError: Module Error (from ./node_modules/next/dist/build/webpack/loaders/error-loader.js):
Global CSS cannot be imported from within node_modules.
Read more: https://err.sh/next.js/css-npm
Location: node_modules/@alDuncanson/react-address-autocomplete/lib/index.js
    at Object.emitError (/Users/prakash/Personal/project/frontend/node_modules/webpack/lib/NormalModule.js:173:6)
    at Object.ErrorLoader (/Users/prakash/Personal/project/frontend/node_modules/next/dist/build/webpack/loaders/error-loader.js:1:1231)
    at LOADER_EXECUTION (/Users/prakash/Personal/project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/prakash/Personal/project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/prakash/Personal/project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/prakash/Personal/project/frontend/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/prakash/Personal/project/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/prakash/Personal/project/frontend/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/prakash/Personal/project/frontend/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)

**Comment by alDuncanson** [comment]
@PrakashTirumalareddy is this error even after rolling back to the previous version? 

What does your `package.json` look like?

**Comment by PrakashTirumalareddy** [comment]
@alDuncanson yes
"dependencies": {
    "@alduncanson/react-address-autocomplete": "1.0.0",
    "@apollo/react-hooks": "3.1.5",
    "@apollo/react-ssr": "3.1.5",
    "@stripe/react-stripe-js": "1.1.2",
    "@stripe/stripe-js": "1.5.0",
    "apollo-boost": "0.4.7",
    "axios": "0.19.2",
    "express": "^4.17.1",
    "graphql": "15.0.0",
    "isomorphic-fetch": "2.2.1",
    "js-cookie": "2.2.1",
    "next": "9.4.0",
    "next-apollo": "3.1.10",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-icons": "^3.10.0",
    "reactstrap": "^8.4.1"
  }

**Comment by alDuncanson** [comment]
Ah, I see you're using `next`. So I believe this issue is unrelated to the `@alDuncanson/react-address-autocomplete` module, and instead is related to [this issue](https://github.com/vercel/next.js/issues/10059)

**Comment by PrakashTirumalareddy** [comment]
@alDuncanson - I see, thank you very much!!!

**Comment by PrakashTirumalareddy** [comment]
https://github.com/vercel/next.js/blob/master/errors/css-npm.md

**Comment by PrakashTirumalareddy** [comment]
@alDuncanson  - is it a big task? is there any temporary fix I can use?

**Comment by alDuncanson** [comment]
@PrakashTirumalareddy I will look into it for you. 

It might take a couple days of testing since I have never shipped a node module with the styles separate like this, but I will try!

**Comment by PrakashTirumalareddy** [comment]
Thanks boss!!!

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-md-editor/issues/52#issuecomment-848969341

Perfect solution.

**Comment by alDuncanson** [comment]
Thanks for the solution @jaywcjlove https://github.com/alDuncanson/react-address-autocomplete/issues/9#issuecomment-850058333
